//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NebuniaLuiFibonacciApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NebuniaLuiFibonacciApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a valid integer!.
        /// </summary>
        public static string ErrorMessage_InvalidIntValue {
            get {
                return ResourceManager.GetString("ErrorMessage_InvalidIntValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string FibDataGrid_Column_Actions {
            get {
                return ResourceManager.GetString("FibDataGrid_Column_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penultimate Term.
        /// </summary>
        public static string FibDataGrid_Column_FirstTerm {
            get {
                return ResourceManager.GetString("FibDataGrid_Column_FirstTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orig. First Term.
        /// </summary>
        public static string FibDataGrid_Column_OriginalFirstTerm {
            get {
                return ResourceManager.GetString("FibDataGrid_Column_OriginalFirstTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orig. Second Term.
        /// </summary>
        public static string FibDataGrid_Column_OriginalSecondTerm {
            get {
                return ResourceManager.GetString("FibDataGrid_Column_OriginalSecondTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Term.
        /// </summary>
        public static string FibDataGrid_Column_SecondTerm {
            get {
                return ResourceManager.GetString("FibDataGrid_Column_SecondTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Term.
        /// </summary>
        public static string FirstTermInput_Label {
            get {
                return ResourceManager.GetString("FirstTermInput_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo Application.
        /// </summary>
        public static string MainWindow_Header {
            get {
                return ResourceManager.GetString("MainWindow_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Mode.
        /// </summary>
        public static string ProcessorSelectionInput_Label {
            get {
                return ResourceManager.GetString("ProcessorSelectionInput_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Fibonacci.
        /// </summary>
        public static string RunProcessButton_Label {
            get {
                return ResourceManager.GetString("RunProcessButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Term.
        /// </summary>
        public static string SecondTermInput_Label {
            get {
                return ResourceManager.GetString("SecondTermInput_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Task.
        /// </summary>
        public static string StartTaskButton_Text {
            get {
                return ResourceManager.GetString("StartTaskButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Task.
        /// </summary>
        public static string StopTaskButton_Text {
            get {
                return ResourceManager.GetString("StopTaskButton_Text", resourceCulture);
            }
        }
    }
}
